CREATE INDEX IF NOT EXISTS session_user ON session (user_id);
CREATE INDEX IF NOT EXISTS account_user ON account (user_id);
CREATE INDEX IF NOT EXISTS account_provider ON account (provider_id, account_id);
CREATE INDEX IF NOT EXISTS verification_identifier ON verification (identifier);
CREATE INDEX IF NOT EXISTS workspace_owner ON workspace (owner_id);
CREATE INDEX IF NOT EXISTS customer_group_ws ON customer_group (workspace_id);
CREATE INDEX IF NOT EXISTS social_account_ws_group ON social_account (workspace_id, group_id);
CREATE INDEX IF NOT EXISTS posts_ws_schedule ON posts (workspace_id, scheduled_at);
CREATE INDEX IF NOT EXISTS posts_ws_status ON posts (workspace_id, status);
CREATE INDEX IF NOT EXISTS posts_parent ON posts (parent_post_id);
CREATE INDEX IF NOT EXISTS posting_set_ws ON posting_set (workspace_id);
CREATE INDEX IF NOT EXISTS signature_ws ON signature (workspace_id);
CREATE INDEX IF NOT EXISTS api_token_hash ON api_token (token_hash);
CREATE INDEX IF NOT EXISTS api_token_ws ON api_token (workspace_id);
CREATE INDEX IF NOT EXISTS outbound_webhook_ws ON outbound_webhook (workspace_id);
CREATE INDEX IF NOT EXISTS plug_trigger ON plug (active, trigger_type);
CREATE INDEX IF NOT EXISTS rss_feed_active ON rss_feed (active);
CREATE INDEX IF NOT EXISTS agent_run_ws ON agent_run (workspace_id, created_at);
CREATE INDEX IF NOT EXISTS workspace_invite_ws ON workspace_invite (workspace_id, status);
